export interface PlaceholderData {
  fecha: string;
  clienteEmpresa: string;
  numeroCotizacion: string;
  detalleDescripcion: string;
  responsable: string;
  estado: string;
  montoTotal: number;
  montoPagado: number;
  montoPendiente: number;
  medioPago: string;
  numeroFactura: string;
  otrosDatos: string;
}

export const placeholderData: PlaceholderData[] = [
  {
    fecha: "2026-06-01",
    clienteEmpresa: "Constructora Andes SpA",
    numeroCotizacion: "COT-1001",
    detalleDescripcion: "Diseño e impresión de material corporativo",
    responsable: "Raúl Espinoza",
    estado: "Pendiente",
    montoTotal: 450000,
    montoPagado: 150000,
    montoPendiente: 300000,
    medioPago: "Transferencia bancaria",
    numeroFactura: "FAC-9001",
    otrosDatos: "Entrega programada para el 15 de junio",
  },
  {
    fecha: "2026-06-02",
    clienteEmpresa: "Innova Tech Ltda",
    numeroCotizacion: "COT-1002",
    detalleDescripcion: "Desarrollo landing page promocional",
    responsable: "Camila Soto",
    estado: "Pagado",
    montoTotal: 780000,
    montoPagado: 780000,
    montoPendiente: 0,
    medioPago: "Tarjeta de crédito",
    numeroFactura: "FAC-9002",
    otrosDatos: "Cliente solicita soporte por 30 días",
  },
  {
    fecha: "2026-06-03",
    clienteEmpresa: "Pet House Chile",
    numeroCotizacion: "COT-1003",
    detalleDescripcion: "Sesión fotográfica para mascotas",
    responsable: "Raúl Espinoza",
    estado: "En proceso",
    montoTotal: 220000,
    montoPagado: 100000,
    montoPendiente: 120000,
    medioPago: "Efectivo",
    numeroFactura: "FAC-9003",
    otrosDatos: "Incluye edición premium",
  },
  {
    fecha: "2026-06-04",
    clienteEmpresa: "Green Market",
    numeroCotizacion: "COT-1004",
    detalleDescripcion: "Diseño de catálogo digital",
    responsable: "Fernanda López",
    estado: "Pendiente",
    montoTotal: 340000,
    montoPagado: 0,
    montoPendiente: 340000,
    medioPago: "Transferencia bancaria",
    numeroFactura: "FAC-9004",
    otrosDatos: "Esperando aprobación final",
  },
  {
    fecha: "2026-06-05",
    clienteEmpresa: "Alpha Seguridad",
    numeroCotizacion: "COT-1005",
    detalleDescripcion: "Impresión de señalética",
    responsable: "Diego Morales",
    estado: "Pagado",
    montoTotal: 125000,
    montoPagado: 125000,
    montoPendiente: 0,
    medioPago: "Cheque",
    numeroFactura: "FAC-9005",
    otrosDatos: "Entrega realizada",
  },
  {
    fecha: "2026-06-06",
    clienteEmpresa: "Nova Retail",
    numeroCotizacion: "COT-1006",
    detalleDescripcion: "Diseño UX/UI aplicación móvil",
    responsable: "Camila Soto",
    estado: "En revisión",
    montoTotal: 950000,
    montoPagado: 400000,
    montoPendiente: 550000,
    medioPago: "Transferencia bancaria",
    numeroFactura: "FAC-9006",
    otrosDatos: "Pendiente feedback del cliente",
  },
  {
    fecha: "2026-06-07",
    clienteEmpresa: "Café Urbano",
    numeroCotizacion: "COT-1007",
    detalleDescripcion: "Branding completo cafetería",
    responsable: "Fernanda López",
    estado: "Cancelado",
    montoTotal: 500000,
    montoPagado: 100000,
    montoPendiente: 400000,
    medioPago: "Efectivo",
    numeroFactura: "FAC-9007",
    otrosDatos: "Proyecto detenido por cliente",
  },
  {
    fecha: "2026-06-08",
    clienteEmpresa: "Logística Sur",
    numeroCotizacion: "COT-1008",
    detalleDescripcion: "Desarrollo sistema inventario",
    responsable: "Raúl Espinoza",
    estado: "En proceso",
    montoTotal: 1450000,
    montoPagado: 700000,
    montoPendiente: 750000,
    medioPago: "Transferencia bancaria",
    numeroFactura: "FAC-9008",
    otrosDatos: "Backend con Supabase",
  },
  {
    fecha: "2026-06-09",
    clienteEmpresa: "Studio Vision",
    numeroCotizacion: "COT-1009",
    detalleDescripcion: "Animación publicitaria 15 segundos",
    responsable: "Diego Morales",
    estado: "Pendiente",
    montoTotal: 610000,
    montoPagado: 200000,
    montoPendiente: 410000,
    medioPago: "PayPal",
    numeroFactura: "FAC-9009",
    otrosDatos: "Incluye 2 rondas de cambios",
  },
  {
    fecha: "2026-06-10",
    clienteEmpresa: "Clínica Dental Norte",
    numeroCotizacion: "COT-1010",
    detalleDescripcion: "Diseño sitio web corporativo",
    responsable: "Camila Soto",
    estado: "Pagado",
    montoTotal: 870000,
    montoPagado: 870000,
    montoPendiente: 0,
    medioPago: "Transferencia bancaria",
    numeroFactura: "FAC-9010",
    otrosDatos: "Hosting incluido por 1 año",
  },
  {
    fecha: "2026-06-11",
    clienteEmpresa: "Electro Hogar",
    numeroCotizacion: "COT-1011",
    detalleDescripcion: "Campaña gráfica Cyber",
    responsable: "Fernanda López",
    estado: "En proceso",
    montoTotal: 390000,
    montoPagado: 190000,
    montoPendiente: 200000,
    medioPago: "Tarjeta de débito",
    numeroFactura: "FAC-9011",
    otrosDatos: "Entrega parcial aprobada",
  },
  {
    fecha: "2026-06-12",
    clienteEmpresa: "Editorial Horizonte",
    numeroCotizacion: "COT-1012",
    detalleDescripcion: "Plataforma de venta de libros usados",
    responsable: "Raúl Espinoza",
    estado: "En desarrollo",
    montoTotal: 2100000,
    montoPagado: 1000000,
    montoPendiente: 1100000,
    medioPago: "Transferencia bancaria",
    numeroFactura: "FAC-9012",
    otrosDatos: "Proyecto conectado a Supabase",
  },
];